### ISSUE TITLE
权限问题汇总

### ISSUE THREAD

**Issue by minghaoye** [kubesphere/kubesphere#1399]
1.workspace regular 没有创建workspace权限，文案写的有

<img width="1280" alt="Screen Shot 2019-11-07 at 10 59 39 AM" src="https://user-images.githubusercontent.com/22934997/68356872-7b8aeb00-014e-11ea-8465-d847d0eb39ea.png">

2.workspace regular 在overview 看见两个project，进入project列表只有一个(没有显示自己没加入的project)

3.workspace regular 新建project后，在project里把自己改为operator，自己被移出项目

4.同3，自己已是admin，把自己改为 admin，同样被移除项目

5.项目 operater 没有权限设置网关

6.项目 operater 没有容器组操作权限

**Comment by minghaoye** [comment]
翻译问题：

<img width="756" alt="Screen Shot 2019-11-07 at 11 21 42 AM" src="https://user-images.githubusercontent.com/22934997/68357601-da516400-0150-11ea-8f8e-ca60e63c3491.png">

@justahole

**Comment by minghaoye** [comment]
翻译：

<img width="1051" alt="Screen Shot 2019-11-07 at 11 54 45 AM" src="https://user-images.githubusercontent.com/22934997/68359048-7e3d0e80-0155-11ea-9966-f4c9662ed322.png">

**Comment by wansir** [comment]
1. 应该是cluster-regular 吧， 无权创建workspace, @leoendless
2. workspace-regular 之间的项目是隔离的，且 workspace regular看不到 worksapce overview 页面，看看是不是切换账号是界面依旧停留在overview 页
3. 修改角色的时候会删除 rolebinding, 这里需要限制一下 不能修改自己的角色 @leoendless 
4. 同上
5. by design ，operator 没有项目高级设置
6. https://github.com/kubesphere/ks-installer/pull/407 fixed

**Comment by leoendless** [comment]
1,3,4 及 翻译问题 Fixed

**Comment by rayzhou2017** [comment]
verified
