### ISSUE TITLE
Feature: 期望支持批量执行多条流水线

### ISSUE THREAD

**Issue by Migo1989** [kubesphere/kubesphere#1811]
我现在有个痛点，想批量同时执行多条流水线部署服务，我看现在kubesphere还不支持，这个功能能提高我们部署的效率。比如说，我们创建了很多服务的流水线，我们勾选想要发布的服务的流水线，然后批量开始执行，期望后续的版本支持一下这个功能

**Comment by LinuxSuRen** [comment]
批量执行流水线的话，可能会有一些潜在的问题需要考虑，例如：部分流水线是参数化的、部分不是。

另外，在特定的场景下，可能是需要执行一系列（有序或者无序）的流水线，我提供另外一个不需要开发的思路：创建一个用于编排这些流水线的流水线，简单来说就是用一个流水线调用其他的流水线；这样的好处就是在处理执行顺序、是否并发等方面会更加容易，而且不需要开发新的功能。

**Comment by LinuxSuRen** [comment]
I think we can close this feature. Because you can see this feature from v3.1.0. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/1450685/101591127-ba146880-3a26-11eb-8598-10f427359827.png)

But I don't know which PR this feature comes from. Please leave a comment if anyone knows it. It will help us to track it.

/cc @shaowenchen 
/cc @Migo1989 
/cc @zryfish

**Comment by LinuxSuRen** [comment]
ping @shaowenchen
