### ISSUE TITLE
The number of project pods in the workbench is not the same as the number of pods in the project overview

### ISSUE THREAD

**Issue by mayuhope** [kubesphere/kubesphere#1861]
Test  steps：
1、The role of user1 is cluster regular + workspace viewer + project operator；
2、Login with user1；
3、On the workbench project page, the number of pods found is 16：
![image](https://user-images.githubusercontent.com/7677050/74407654-61f3f080-4e6d-11ea-85ba-60fa7c74fa2f.png)

4、Enter the project and find that the number of pods is 17 on the project overview page
<img width="733" alt="1581575635(1)" src="https://user-images.githubusercontent.com/7677050/74407887-e9416400-4e6d-11ea-8b47-e197f2939c73.png">

5、There is a pod in the project, and its status is Unschedulable：
<img width="955" alt="1581575745" src="https://user-images.githubusercontent.com/7677050/74407984-30c7f000-4e6e-11ea-83a5-10473f6e0b79.png">

**Comment by huanggze** [comment]
We have pod count of different definition in different context

For example, pod count for:
- Running Pods: pods in the Running phase
- Non-terminated Pods: pods in any phase rather than Succeeded and Failed
- Overall Pods: pods in any phase
- Abnormal Pods: taking both pod condition and pod phase into consider

Let's settle down this inconsistency in 3.0.0
