### ISSUE TITLE
Pipeline should throw error msg

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#1913]
* [ ] In all-in-one, when CPU is insufficient, the pipeline is in queued status without any msg, which confuses users.
<img width="1195" alt="Screen Shot 2020-02-21 at 8 04 15 PM" src="https://user-images.githubusercontent.com/28859385/75035245-061f0c80-54ea-11ea-81bc-9698db5a3a63.png">

**Comment by runzexia** [comment]
This problem is not easy to solve in 2.1.1.
When the pipeline is in the queue state, Jenkins will determine whether to start a new agent. The binding relationship between the pipeline and the agent will not be established until the agent is ready.
This makes it inconvenient for us to directly use the API to view the status of the agent corresponding to the pipeline.

**Comment by benjaminhuo** [comment]
This is easy to fix in 3.1.0 now? @shaowenchen

**Comment by shaowenchen** [comment]
> This is easy to fix in 3.1.0 now? @shaowenchen

It's not easy. Please remove it from milestone 3.1.0.
