### ISSUE TITLE
does 3.0.0 support istio 1.5.0 ？

### ISSUE THREAD

**Issue by sd797994** [kubesphere/kubesphere#1969]
istio released their new version 1.5.0 in Mar, In this version they reduce the scale of application to simplifies deployments. Does community plan to support it in version 3.0.0?

**Comment by sammasamadhi** [comment]
same question

**Comment by rayzhou2017** [comment]
We will investigate this upgrade later on. Well, I would rather put the label for help on it now.

**Comment by juan-vg** [comment]
I would suggest to move directly to 1.6.x as they have fixed some upgrade stuff regarding helm and the new control plane (istiod) approach

**Comment by FeynmanZhou** [comment]
> I would suggest to move directly to 1.6.x as they have fixed some upgrade stuff regarding helm and the new control plane (istiod) approach

@juan-vg +1. As @zryfish mentioned previously, we will bring Istio 1.6.x in v3.1.

**Comment by zryfish** [comment]
KubeSphere v2.1.1 uses istio 1.3.x, Users should not upgrade 1.3.x to 1.5.x directly since this is not backed by the istio community, it's not safe. We are upgrading istio to 1.4.8, the latest version of 1.4.x in v3.0, and planning to upgrade a newer version in v3.1.

**Comment by juan-vg** [comment]
@zryfish AFAIK it's not recommended, but it's backed to migrate to 1.6 directly since the migration from 1.4 to 1.5 is broken when using helm, as [it has been discussed on Istio's github issues](https://github.com/istio/istio/issues/22874#issuecomment-614682792). On the other hand, I don't see any issue on running more than one upgrade on Istio when migrating to v3.0

Moreover, here comes another fact to keep in mind! From Istio 1.5 helm is not anymore recommended to perform the upgrades, which should be done using istioctl
