### ISSUE TITLE
How to use external etcd and es

### ISSUE THREAD

**Issue by Ruilkyu** [kubesphere/kubesphere#2103]

**Comment by yunkunrao** [comment]
Hi, you can ask questons about kubesphere usage in [kubesphere developer forum](https://kubesphere.com.cn/forum/).

**Comment by FeynmanZhou** [comment]
@Ruilkyu 
external etcd: https://kubesphere.com.cn/forum/d/1386-kubesphere-etcd
external ES can be configured before or after KubeSphere installation. If you haven't install KubeSphere yet, refer to the installation guide, it has an explanation for it. Otherwise, you can refer to this [guide](https://kubesphere.com.cn/docs/zh-CN/platform-settings/log-gathering/)
