### ISSUE TITLE
custom role of project is incorrect

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2397]
**Describe the Bug**
A custom role of project without custom monitoring dashboard access still can see custom monitoring dashboard
<img width="870" alt="Screen Shot 2020-07-11 at 10 26 21 AM" src="https://user-images.githubusercontent.com/28859385/87214665-48de6580-c361-11ea-80ea-14e60a495dbe.png">
<img width="793" alt="Screen Shot 2020-07-11 at 10 26 34 AM" src="https://user-images.githubusercontent.com/28859385/87214667-4ed44680-c361-11ea-9c2b-534d308e4745.png">
<img width="1242" alt="Screen Shot 2020-07-11 at 10 26 44 AM" src="https://user-images.githubusercontent.com/28859385/87214669-5398fa80-c361-11ea-95a4-61a026be1a4e.png">

**Versions Used**
KubeSphere: 3.0.0-dev

**Environment**
allinone, minimal installation

**How To Reproduce**
1. log in as self-provisioner, create a custom project role without custom monitoring dashboard access and assign a user with the new role
2. log in as the user with the new custom role
3. the user can see the custom monitoring dashboard

**Expected behavior**
The user with the custom role is not able to view custom monitoring dashboard.

**Comment by wansir** [comment]
The role template `role-template-view-projects` in the workspace means to authorize the viewing rights of all projects in the workspace, we use the tenant API to list user's namespace (user-related resources)  in the workspace, the nav button not controlled by `role-template-view-projects`， everyone in the workspace has rights to call the tenant API. User has `role-template-view-projects` permission can list all projects in the workspace, otherwise only the projects that the user joined will be returned. 

@leoendless `role-template-view-projects` will not exist in the permission list of regular workspace members.

**Comment by rayzhou2017** [comment]
verified
