### ISSUE TITLE
the problem of deleting the volume snapshot

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/kubesphere#2809]
**Describe the Bug**
Delete the volume snapshot, indicating that the deletion was successful, but it still exists in the list and needs to wait for a while before it disappears from the list
And the status has not been updated to deleting

<img width="684" alt="deleting" src="https://user-images.githubusercontent.com/36271543/89701938-6b6a9b00-d96e-11ea-9ecb-42940c522591.png">

/kind bug
/area console
/assign @leoendless
/milestone 3.0.0
/priority medium

**Comment by stoneshi-yunify** [comment]
I think this is a KS console/UI bug. The fix might be:
- when get a 200 OK response for the delete volumesnapshot request, should show a "deleting" rather than "deletion successful" notification in the right upper corner. Meanwhile, change the snapshot's status to "deleting" in the snapshot list.
- poll snapshot list repeatedly, when the deleting snapshot is not the list (means it is actually deleted), stop poll, and show a "deletion successful" notification in the right upper corner of the page.
- A deletion timeout might be set, say if the deletion can not complete in 60 seconds, show a "deletion failed" notification.

@leoendless please take a look, thanks.

**Comment by leoendless** [comment]
Just update the status of snapshot crd resource. The console will update the list from the websocket message.
