### ISSUE TITLE
kubesphere login error!

### ISSUE THREAD

**Issue by yanruogu** [kubesphere/kubesphere#2835]
I installed kubesphere 3.0.

when I want to login.  now error like this: 

![image](https://user-images.githubusercontent.com/5188514/89802763-80a91a80-db64-11ea-91ba-936635ecbda5.png)

How can I fix it ?

**Comment by yanruogu** [comment]
error like this: Internal error occurred: the server could not find the requested resource (post loginrecords.iam.kubesphere.io)

**Comment by zryfish** [comment]
It happens when you upgrade components without upgrading ks-installer, there are some CRD files missing. You can either

1. reinstall the KubeSphere or  
2.  `kubectl create -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/common/files/ks-crds/iam.kubesphere.io_loginrecords.yaml`   

the second option may not work cause there are other configurations missing if you don't upgrade ks-installer, but you can have a try first.

**Comment by yanruogu** [comment]
thank you.  It's resovled

**Comment by zryfish** [comment]
/close
due to problem resoloved
