### ISSUE TITLE
Upgrade from 2.1.1 to 3.0.0 custom cluster/platform role and project role authorization list missing

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/kubesphere#2909]
**Describe the Bug**
before upgrading, create two custom role, a cluster role and a project role. All are authorized some resources. But the resources are gone after upgrade.

![Screen Shot 2020-08-21 at 2 14 54 PM](https://user-images.githubusercontent.com/28859385/90858599-20627600-e3b9-11ea-9f58-f6123f083c73.png)
![Screen Shot 2020-08-21 at 2 14 04 PM](https://user-images.githubusercontent.com/28859385/90858614-26585700-e3b9-11ea-86ed-07b5c10a4328.png)

**Comment by wansir** [comment]
Custom roles are upgraded according to the policy rules. Some rules are invalid in 3.0. Only the following rules can be upgraded. Otherwise, need to check the permissions again.

upgrade rules:
https://github.com/kubesphere/ks-upgrade/blob/master/pkg/globalrolebindings/globalrolebindings.go#L113-L230
https://github.com/kubesphere/ks-upgrade/blob/master/pkg/rolebindings/rolebindings.go#L182-L347

**Comment by rayzhou2017** [comment]
OK, that is also what I am thinking. We need to write a doc for it from the console authorization list point of view. So users know what is going to happen, and what they should do in terms of the roles after upgrade.

**Comment by wansir** [comment]
We need to provide documentation to tell the user what has changed and how to define the role he wants through the console, I'll do this.
