### ISSUE TITLE
cannot stat '/var/jenkins_config/*.groovy': No such file or directory

### ISSUE THREAD

**Issue by MRGUO840140** [kubesphere/kubesphere#3170]
## English only!

**注意！GitHub Issue 仅支持英文，中文 Issue 请在 [论坛](https://kubesphere.com.cn/forum/) 提交。**

**General remarks**

> Please delete this section including header before submitting
>
> This form is to report installation issues. For general usage questions you can refer to [KubeSphere Documentation](https://kubesphere.io/docs) or join our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTZkNTdkYWNiYTVkMTM5ZThhODY1MjAyZmVlYWEwZmQ3ODQ1NmM1MGVkNWEzZTRhNzk0MzM5MmY4NDc3ZWVhMjE)

**What's your question**

**Environment: OS & Hardware Information**

> Important: You must describe your environment clearly, e.g. VMware or Bare Metal, CentOS 7.5, 8 C / 16 G (If you install on Linux), Or Kubernetes v1.16 (If you install on K8s).

**Error logs or message (Attach logs or screenshot)**

**Installer Version**

> e.g. v2.1.0, v2.1.1, v3.0.0

**Comment by shaowenchen** [comment]
Please use ks-installer:v3.0.0 to install it currently.

/assign @LinuxSuRen

**Comment by LinuxSuRen** [comment]
hi @MRGUO840140, thanks for reporting this issue. I believe this https://github.com/kubesphere/ks-installer/pull/1174 can fix it.
A friendly tip for you. Please be careful when you try to use the latest docker image or the images come from `kubespheredev/xxx`. Of course, if you just want to try something new instead of deploying it to a stable environment, it's ok for using images from `kubespherdev/xxx`.

**Comment by LinuxSuRen** [comment]
This was fixed in https://github.com/kubesphere/ks-installer/pull/1174. I believe that we can close this @MRGUO840140
