### ISSUE TITLE
Multi-cluster mode Multi-Harbor Down image faild

### ISSUE THREAD

**Issue by vincenthe-ks** [kubesphere/kubesphere#3295]
**Describe the Bug**
Multi-cluster mode:
hosts: 3master + 2node  Harbor: mgmt.cloud.com
member: 3master + 9 node Harbor: test.cloud.com

When I login hosts cluster， select the member cluster to deploy bookinfo。
default image: mgmt.cloud.com/kubesphere/examples-bookinfo-reviews-v1:1.13.0
The correct image should be： test.cloud.com/kubesphere/examples-bookinfo-reviews-v1:1.13.0

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
hosts: 3master + 2node harbor: mgmt.cloud.com
member: 3master + 9 node harbor: test.cloud.com

select memeber cluster
1. Click on 'Application'
2. Click on 'Deploy Sample  Application'
![image](https://user-images.githubusercontent.com/8400716/105660338-c173d080-5f05-11eb-9c5e-5589ad963946.png)
![image](https://user-images.githubusercontent.com/8400716/105660437-f8e27d00-5f05-11eb-822e-0352b39c3e97.png)

**Expected behavior**

**Comment by RolandMa1986** [comment]
Looks like this is worked as designed. pls, help confirm. @zackzhangkai

**Comment by zackzhangkai** [comment]
@hewenhong Go to the member cluster, to deploy a sample bookinfo. Check what the image shows. I think it's because of the wrong configure of your docker registry on each node.

**Comment by zackzhangkai** [comment]
@yuswift  Enter host console, then go to the member, should set the registry of member as default, instead of the host.

![image](https://user-images.githubusercontent.com/20178386/114492471-3f18c400-9c4b-11eb-898a-f5a0322741e3.png)

Such as deploy the sample bookinfo, because the default is the host registry,  it results into a wrong config.

![image](https://user-images.githubusercontent.com/20178386/114492702-a9c9ff80-9c4b-11eb-8586-7aca65f7b3b9.png)
