### ISSUE TITLE
v3.0.0 All-in-One installation download package SHA256 no match

### ISSUE THREAD

**Issue by kevinpan45** [kubesphere/kubesphere#3313]
**What's your question**
Install v3.0.0 follow
https://kubesphere.com.cn/docs/quick-start/all-in-one-on-linux/

download package SHA256 no match

**Environment: OS & Hardware Information**

CentOS 7.6

**Error logs or message (Attach logs or screenshot)**
install command
`./kk create cluster --with-kubernetes v1.17.9 --with-kubesphere v3.0.0`
error msg
`Failed to download kube binaries: Failed to load kube binaries: SHA256 no match. 2ca83eecd221bedf3eceb0ccfcf45bb2e27950c382c2326211303adb0a9c4232 not in 54e7592bb6fedfc12190fb810cf684a87c5316fcffeeacecad99aecbf8ca4860  /root/kubekey/v1.17.9/amd64/kubectl`

**Installer Version**

> v3.0.0

**Comment by rayzhou2017** [comment]
delete kubekey folder in your machine first.

**Comment by LinuxSuRen** [comment]
hi @kevinpan45 , it might be caused by an incomplete process. This [PR](https://github.com/kubesphere/kubekey/pull/425/files#diff-f71dcc250e0d3df80d3819f40b9e81560e471b12f2a3528f280dd8702ef29864R83) intend to fix it. You can try it again with the latest kk. But you might need to compile kk from the source.

**Comment by kevinpan45** [comment]
> delete kubekey folder in your machine first.

it work
