### ISSUE TITLE
How to modify the mail template?

### ISSUE THREAD

**Issue by Du-fei** [kubesphere/kubesphere#3379]
**What's it about?**

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* case one
* case two
* ...

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request

**Comment by LinuxSuRen** [comment]
It looks like a support request instead of a feature request. Furthermore, please follow the template of the issue, and provide the details as possible as you can. I cannot understand what do you want to know.

In my view, the issue area is not a good place to ask questions or seek support. We encourage people to request feature support, bugs, proposals here. You can try to start a new topic from [discussion](https://github.com/kubesphere/kubesphere/discussions).

/kind support
