### ISSUE TITLE
Unable to enter the credential details in the member cluster

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#3639]
**Environment**
host 3.1 + member 3.0

http://139.198.9.112:30883

**How To Reproduce**
1. Go to workspace 'ws1'
2. Go to devops 'dev1'
3. Clcik on 'Credentials'
4. Click name of Credentials

**Expected behavior**
enter the credential details

**Actual behavior**
can not click the name of Credential

![image](https://user-images.githubusercontent.com/68640256/112944801-ed117200-9165-11eb-9c58-6566f4dabeaf.png)

/priority high
/area devops
/cc @kubesphere/sig-devops
/kind bug
/milestone 3.1.0

**Comment by LinuxSuRen** [comment]
I repeated it following your steps. The credentials work well. The problem is that the console of 3.1.0 (not released yet, the same with the following expression) has a restriction about the view action. So if the host cluster is 3.1.0, the member cluster is 3.0.0, then users cannot view the detail of the DevOps credential.

But if the host cluster is 3.0.0, the member cluster is 3.1.0. It should be work.

In my opinion, there's no necessary to restrict users to view or edit the credential base on the sync status. I would suggest deleting the column `Sync Status`. It makes people feel confused. People can check the sync status in the detail area.

![image](https://user-images.githubusercontent.com/1450685/113252954-1ca3b400-92f7-11eb-81b0-ca11e79e228b.png)

/area console

**Comment by zryfish** [comment]
how about hide column `Sync status` by default?

**Comment by LinuxSuRen** [comment]
> how about hide column `Sync status` by default?

It might not be easy to hide. Put the information into the detail area which users can see it after going to the detail page.

**Comment by zryfish** [comment]
> > how about hide column `Sync status` by default?
> 
> It might not be easy to hide. Put the information into the detail area which users can see it after going to the detail page.

OK, fine with me.

**Comment by LinuxSuRen** [comment]
/kind need-to-verify

See also https://github.com/kubesphere/console/pull/1761

**Comment by LinuxSuRen** [comment]
Test pass in `nightly-20210411`

/close
