### ISSUE TITLE
ks-apiservef panic due to a potential storageclass related issues

### ISSUE THREAD

**Issue by waidinsamkeit** [kubesphere/kubesphere#3746]
# Apiserver日志
![image](https://user-images.githubusercontent.com/52663349/114960902-8ea0ff00-9e9a-11eb-9145-bcdf1001dbd5.png)
# 所有已经绑定的存储类
![image](https://user-images.githubusercontent.com/52663349/114960927-995b9400-9e9a-11eb-9a2c-e1ae9276e491.png)
已经按照社区方法都试过了 增加storageclassname 什么的 都不好使
现在apisherver依旧报错这个

**Comment by waidinsamkeit** [comment]
![image](https://user-images.githubusercontent.com/52663349/114961054-dcb60280-9e9a-11eb-8013-f302ab1c4deb.png)

**Comment by LinuxSuRen** [comment]
Hi @waidinsamkeit , thanks for reporting this issue. If you can take some time to provide more context, for example, Kubernetes and KubeSphere version, I might be able to get help quickly. For my side, I don't know how to reproduce it according to your description.

/retitle ks-apiservef panic due to a potential storageclass related issues

**Comment by waidinsamkeit** [comment]
> 嗨，@waidinsamkeit，谢谢你报道这个问题。如果你可以花一些时间来提供更多的上下文，例如，库伯内特和库贝圈版本，我也许能够迅速得到帮助。对于我这边，我不知道如何根据你的描述复制它。
> 
> /重新标题ks-apiservef恐慌由于潜在的存储类相关问题
> /种错误

已经解决 希望可以在下个版本修复需要指定storageclassName的问题
