### ISSUE TITLE
affect workloads prompt is incorrect

### ISSUE THREAD

**Issue by wansir** [kubesphere/kubesphere#4276]
**Describe the Bug**

When creating a service with a specified label selector, the affect workloads prompt is incorrect.

> Route service traffic to pods with label keys and values matching this selector.

/kind bug

![image](https://user-images.githubusercontent.com/8263040/134642247-c6cc84b3-a7c7-4439-9a39-3ad7e7e5bccd.png)

**Versions Used**
KubeSphere: v3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

Match workloads with `spec.selector.matchLabels`

**Comment by RolandMa1986** [comment]
/area console
When I tested with KubeSphere v3.2.0, the labels do match with spec.selector.matchLabels. However, it was showing "The current selector matches no workload." on the UI. I think the Service Selector only matches with pods in the Kubernetes design, instead of workload(Deployment/Statefullset).
