### ISSUE TITLE
After differentiated editing, the editing pod template does not take effect

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4352]
**Describe the Bug**
1. Differentiately edit container images,click save,click to confirm, pod updated successfully，image changed
2. Edit the container, modify the container image，pod not changing

https://user-images.githubusercontent.com/88183150/136772298-a45d6c81-6a55-4855-8879-683b975cc1b8.mp4

**Versions Used**
KubeSphere: v3.2.0-alpha.1

/kind bug
/@kubesphere/sig-kubesphere
/priority high

**Comment by zryfish** [comment]
It works as expected. Since the first step you did is to override the image of the control-plane cluster, the override will be kept even you choose another image for all clusters.  So the images of clusters will be like
1. Before differentiated editing, control-plane: nginx member: nginx
2. After, control-plane: crouchdb member: nginx
3. Choose redis, control-plane: crouchdb member: nginx

So, it's expected the control-plane doesn't redeploy pods. You need to undo differentiated editing if you want to set image from container template.
