### ISSUE TITLE
Failed to edit FederatedStatefulSet with not ready status

### ISSUE THREAD

**Issue by jioce** [kubesphere/kubesphere#4411]
**Describe the Bug**
There is a federated FederatedStatefulSet, the mirror is nginx, and the port is 80
1.Add a ready probe for the FederatedStatefulSet, set up HTTP inspection, port is 81,click save
2. The pod status is consistently not ready
3. change the probe port to 80, the update fails, and the pod is not updated
The same problem exists when starting the probe

https://user-images.githubusercontent.com/88183150/139798757-58d76e65-924a-4851-b62a-6ffd109c8b8d.mp4

1.There is a FederatedStatefulSet, there are two containers, an initial container image is nginx, and a working container image is tomcat，Pod status is initializing
2.Change the image of the initial container to busybox, and the pod will not be updated

https://user-images.githubusercontent.com/88183150/139799961-24a6b441-e63b-416c-a7ae-e29b326e94f3.mp4

**Versions Used**
KubeSphere: v3.2.0

/kind bug
/@kubesphere/sig-kubesphere
/priority low

**Comment by iawia002** [comment]
I don't think it's a bug, it's an awkward situation, in fact, `FederatedStatefulSet` and `StatefulSet` both updated successfully, just because `StatefulSet` is waiting for the original `Pod` to start successfully before updating, but the previous `Pod` is stuck in `Running` but not `Ready` state because of the health check, so the update will be stuck, if you delete the previous `Pod` manually it will update normally.

**Comment by wenxin-01** [comment]
In my opinion, after the configuration is modified, the original pod should be automatically deleted, and then a new pod is created based on the new configuration. Instead of manually deleting the previous pod.

**Comment by jioce** [comment]
issue is not fixed

**Comment by jioce** [comment]
issue is not fixed
