### ISSUE TITLE
The kubesphere 3.2 linked the 3.1 documentation

### ISSUE THREAD

**Issue by hurricane1988** [kubesphere/kubesphere#4492]
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by FeynmanZhou** [comment]
Hi @hurricane1988 , thanks for reporting this issue. It has been fixed in v3.2.1, see [this PR](https://github.com/kubesphere/console/pull/2628/files). 

But I think it is supposed to direct the documentation links of KubeSphere Console to `https://v3-2.docs.kubesphere.io/docs/xxx` instead of the latest URL (`https://kubesphere.io/docs/xxx`). Otherwise, some latest URLs might be broken after v3.3.0 is released.
