### ISSUE TITLE
when i upgrade project gateway , can't change gateway configure

### ISSUE THREAD

**Issue by xwb-spec** [kubesphere/kubesphere#4513]
this is my error log ![image](https://user-images.githubusercontent.com/13009409/144779272-8f051f31-9bc4-4a29-a1e3-fdd1a4923773.png)

**Comment by gzdreamfly** [comment]
when my cluster gateway open ,if i closed project gateway, how i open it

**Comment by gzdreamfly** [comment]
E1203 05:06:02.870348       7 event.go:273] Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kubesphere-router-lrs-tt-f588f9dcb-kjtnm.16bcf1af221a6af6", GenerateName:"", Namespace:"kubesphere-controls-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kubesphere-controls-system", Name:"kubesphere-router-lrs-tt-f588f9dcb-kjtnm", UID:"0fce1e63-d767-4e1d-87f7-584b3d3a3ee1", APIVersion:"v1", ResourceVersion:"25467181", FieldPath:""}, Reason:"RELOAD", Message:"NGINX reload triggered due to a change in configuration", Source:v1.EventSource{Component:"nginx-ingress-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xc0624eccb89bf6f6, ext:1768276977, loc:(*time.Location)(0x2686160)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xc06287358cdad7e4, ext:57765034200256, loc:(*time.Location)(0x2686160)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'can't patch an event with namespace 'kubesphere-controls-system' in namespace 'lrs-tt''(may retry after sleeping)

**Comment by gzdreamfly** [comment]
![image](https://user-images.githubusercontent.com/13009409/144818988-3697de93-4fbd-494d-9e61-56c2340dadbb.png)

when i close cluster gateway, the error occured

**Comment by zryfish** [comment]
Please follow the template, and describe how to reproduce step by step.
