### ISSUE TITLE
Is the source code of edge watcher open source

### ISSUE THREAD

**Issue by Phoaster-wry** [kubesphere/kubesphere#4690]
Is the source code of edge-watcher open source

**Comment by zhu733756** [comment]
Edge-watcher controller aims to open up the kubeEdge monitoring link without manually adding iptables rules.  This is very useful for lower versions of KubeEdge. However, the upstream has supported automatic forwarding rule operation and maintenance since kubeedge v1.8.0+. Our integration efforts will be consistent upstream, so in the future, this component will be obsolete and open source won't make much sense.

**Comment by FeynmanZhou** [comment]
> Edge-watcher controller aims to open up the kubeEdge monitoring link without manually adding iptables rules. This is very useful for lower versions of KubeEdge. However, the upstream has supported automatic forwarding rule operation and maintenance since kubeedge v1.8.0+. Our integration efforts will be consistent with upstream, so in the future, this component will be obsolete and open source won't make much sense.

Thanks for the explanation. Is this component `kubesphere/edge-watcher` make sense for users if they are still using the elderly version?

**Comment by benjaminhuo** [comment]
kubesphere/edge-watcher is not open-sourced and there is no plan to open source it for now.
The source code could be provided to commercial users.
