### ISSUE TITLE
Failed to add cluster(Direct Connection)

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#4807]
**Describe the Bug**
![image](https://user-images.githubusercontent.com/68640256/164131280-1ee2c3f2-ca1a-495c-a71f-acf657704fa7.png)

`kubectl logs -f kubefed-controller-manager-xxxxx -n kube-federation-system`
![image](https://user-images.githubusercontent.com/68640256/164131376-ff12233a-f3cf-4075-ab6b-3497c1b8ee7d.png)

**Versions Used**
KubeSphere:   `v3.3.0-alpha.1`

/priority high
/assign @iawia002

**Comment by iawia002** [comment]
The description is not accurate, the cluster is successfully added and the status is normal, the problem is caused by the failure of the `ClusterClient` component to cache the cluster:

https://github.com/kubesphere/kubesphere/blob/0086e98288e9761bc3dd8d27007e9640fd967bd5/pkg/utils/clusterclient/clusterclient.go#L202-L210

https://github.com/kubesphere/kubesphere/blob/7d9563dca1e5d4f81615b7a1e650f7c991fe31cd/pkg/apiserver/dispatch/dispatch.go#L64

For now, I do not know why the cache was not successful, the `ks-apiserver` Pod was restarted, the previous logs were not found, we need more logs to locate this problem.

**Comment by iawia002** [comment]
When this happens, `ks-apiserver` has no associated error logs and I don't know what the problem is.

@xyz-li since you are the original author of the `ClusterClient` component, can you help to locate this problem?

/assign @xyz-li

**Comment by xyz-li** [comment]
Interesting. 
After I deleted and added the cluster two times, the bug still exists.
I have no idea about this bug now.

**Comment by shihaoH** [comment]
After I directly connect the ACK cluster, there is also a situation where the cluster does not exist
my issue https://kubesphere.com.cn/forum/d/7122-hostack

**Comment by wenxin-01** [comment]
issue fix in `kubespheredev/ks-apiserver:nightly-20220427`
