### ISSUE TITLE
Added crd method to store user access credentials

### ISSUE THREAD

**Issue by x893675** [kubesphere/kubesphere#4817]
**What's it about?**

Added token crd method to store user access credentials instead of redis

**What's the reason why we need it?**

I believe this is an important feature for Kubesphere. There're a few use cases:

* During our use, we found that the redis pod often crashed, causing kubesphere to not work properly
* The deployment of redis ha cluster on k8s is more complicated. Removing the redis component can make kubesphere more lightweight

Please leave your comments below if there's anyone agrees with me. Or just give me a thumb up.

**Area Suggestion**

/kind feature-request
/area apiserver

**Comment by wansir** [comment]
Currently, Redis is only used for token persistence, it's a useful feature if you need to manage user sessions or revoke issued tokens. Redis is not necessary, and you can use the in-memory cache only. Cache all data to etcd is not a good idea, maybe we can provide more data persistence configurations such as local storage, MySQL, etc...

**Comment by wansir** [comment]
First, we need to support the configuration of the token cache. Currently, it is related to the number of the master nodes, manual configuration should be supported.

**Comment by x893675** [comment]
I think in-memory cache is only used in all-in-one env and test env. In other cases, data of user session should be persisted.

The amount of user data will not be too large, and when using ks  through the host under multi-cluster, only the host cluster will store the token, I think it is tolerable to store it in etcd.   use local storage, MySQL and other methods has the same problem as redis.

**Comment by wansir** [comment]
CRD is not a good choice, it's different from the access token used for the service account. Non-resource data should not be cached to etcd, using the auth API in a wrong way will cause the etcd pressure. Redis is a common caching solution, maybe HA mode brings complexity, it should be configurable.

/assign @zhou1203

**Comment by zhou1203** [comment]
### Community Questions:
Using Redis components and the default is cluster mode, the dependencies are too heavy and the cost is too high.

### Background:
Redis is mainly used to store `JWT` in KS for user authentication.
>**Question: Why does Redis need to store `Token` when there is already `JWT`?**
JWT doesn`t support manual Token revocation, and can only be invalidated after the token expires. However, due to security considerations, the Token must be manually revoked, so the double verification mechanism of JWT expiration time and cached Token is used. This supports user logout and session management.

### Current solution:
A cache interface is provided in KS to support data caching, sharing, and deletion.

Two implementations are provided for different scenarios:
 1. **in-memory cache**: usually used in All-In-One installation, test environment, use in-memory cache in single-copy case, no additional component dependencies.
 2. **Redis**: In a multi-node environment, KS will enable high-availability mode by default. At this time, ks-apiserver has multiple copies, and Redis needs to be used to achieve data caching and sharing.

### Improvement strategy:
**Support more cache configuration options, Redis deployment mode can be adjusted.**

* Non-high-availability installation: By default, ks-apiserver only retains one copy and uses in-memory cache.
* High availability installation: ks-apiserver can configure more cache options (ETCD\MYSQL\REDIS, etc.), when using Redis, you can choose cluster or single copy mode.

***Bug**: There perhaps cause memory leaks at in-memory cache mode. Under normal circumstances, the user login will cache the issued token, but the in-memory cache does not clean the token when JWT expired. The user must log out to clear the memory, which needs to be cleaned up regularly.*
