### ISSUE TITLE
KubeSphere 2.0.1 安装失败 ：no matches for kind \"S2iBuilderTemplate\

### ISSUE THREAD

**Issue by alex8158** [kubesphere/kubesphere#499]
安装KubeSphere 2.0.1时报错：
TASK [ks-devops/s2i : S2I | Deploy S2I template&&operator] *********************************************************************************************************
Wednesday 19 June 2019  10:48:52 +0800 (0:00:02.092)       0:09:16.843 ******** 
failed: [ksm1] (item=java.yaml) => {"changed": true, "cmd": "/usr/local/bin/kubectl apply -f /etc/kubesphere/s2i/java.yaml", "delta": "0:00:00.954746", "end": "2019-06-19 10:48:53.557794", "item": "java.yaml", "msg": "non-zero return code", "rc": 1, "start": "2019-06-19 10:48:52.603048", "stderr": "error: unable to recognize \"/etc/kubesphere/s2i/java.yaml\": no matches for kind \"S2iBuilderTemplate\" in version \"devops.kubesphere.io/v1alpha1\"", "stderr_lines": ["error: unable to recognize \"/etc/kubesphere/s2i/java.yaml\": no matches for kind \"S2iBuilderTemplate\" in version \"devops.kubesphere.io/v1alpha1\""], "stdout": "", "stdout_lines": []}
failed: [ksm1] (item=nodejs.yaml) => {"changed": true, "cmd": "/usr/local/bin/kubectl apply -f /etc/kubesphere/s2i/nodejs.yaml", "delta": "0:00:01.154140", "end": "2019-06-19 10:48:54.893544", "item": "nodejs.yaml", "msg": "non-zero return code", "rc": 1, "start": "2019-06-19 10:48:53.739404", "stderr": "error: unable to recognize \"/etc/kubesphere/s2i/nodejs.yaml\": no matches for kind \"S2iBuilderTemplate\" in version \"devops.kubesphere.io/v1alpha1\"", "stderr_lines": ["error: unable to recognize \"/etc/kubesphere/s2i/nodejs.yaml\": no matches for kind \"S2iBuilderTemplate\" in version \"devops.kubesphere.io/v1alpha1\""], "stdout": "", "stdout_lines": []}
操作系统版本是centos 7.6
# docker -v
Docker version 18.06.2-ce, build 6d37f41

**Comment by pixiake** [comment]
这个有可能是创建这些yaml对象时，相关的crd还没有完全写入，重新执行一遍安装应该就可以了

**Comment by alex8158** [comment]
接着直接重新执行安装，又报以下错误，重复多次安装都是这个错：
fatal: [ksm1]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.169315", "end": "2019-06-25 09:38:14.840653", "rc": 0, "start": "2019-06-25 09:38:14.671338", "stderr": "", "stderr_lines": [], "stdout": "Pending", "stdout_lines": ["Pending"]}

**Comment by pixiake** [comment]
这个一般是由于存储配置有问题或者存储服务端不可用造成的，可以检查下是存储的相关配置

**Comment by alex8158** [comment]
我只是启用了nfs，vars.yml配置如下：
##config
## Please configure the API service, if your cluster based on QingCloud IaaS
## platform and want to use qingcloud-csi or qingcloud-cloud-controller-manager.
# Access key pair can be created in QingCloud console
#qingcloud_access_key_id: ACCESS_KEY_ID
#qingcloud_secret_access_key: ACCESS_KEY_SECRET
# Zone should be the same as Kubernetes cluster
#qingcloud_zone: ZONE
# QingCloud IaaS platform service url.
#qingcloud_host: api.qingcloud.com
#qingcloud_port: 443
##qingcloud_protocol: https
#qingcloud_uri: /iaas
#qingcloud_connection_retries: 3
#qingcloud_connection_timeout: 30

## If you want to use QingCloud LoadBlancer Plugin, please reference the documentation for installation instructions.
## https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/qingcloud-lb
qingcloud_lb_enable: false
#qingcloud_vxnet_id: SHOULD_BE_REPLACED
######################################################################
# Storage configuration
######################################################################
## https://docs.kubesphere.io/advanced-v2.0/zh-CN/installation/storage-configuration

# Local volume provisioner deployment(Only all-in-one)
#local_volume_provisioner_enabled: true
#local_volume_provisioner_storage_class: local
#local_volume_is_default_class: true

# QingCloud CSI
qingcloud_csi_enabled: false
qingcloud_csi_is_default_class: false
#The type of volume in QingCloud IaaS platform.
# 0 represents high performance volume
# 3 respresents super high performance volume.
# 1 or 2 represents high capacity volume depending on cluste's zone
# 5 represents enterprise distributed SAN (NeonSAN) volume
# 100 represents basic volume
# 200 represents SSD enterprise volume.
#qingcloud_type: 2
#qingcloud_maxSize: 5000
#qingcloud_minSize: 100
#qingcloud_stepSize: 50
#qingcloud_fsType: ext4
# 1 means single replica, 2 means multiple replicas. Default 2.
#qingcloud_disk_replica: 2

# Ceph_rbd  deployment
ceph_rbd_enabled: false
ceph_rbd_is_default_class: false
#ceph_rbd_storage_class: rbd
# e.g. ceph_rbd_monitors:
#   - 172.24.0.1:6789
#   - 172.24.0.2:6789
#   - 172.24.0.3:6789
#ceph_rbd_monitors:
#  - SHOULD_BE_REPLACED
#ceph_rbd_admin_id: admin
# e.g. ceph_rbd_admin_secret: AQAnwihbXo+uDxAAD0HmWziVgTaAdai90IzZ6Q==
#ceph_rbd_admin_secret: SHOULD_BE_REPLACED
#ceph_rbd_pool: rbd
#ceph_rbd_user_id: admin
# e.g. ceph_rbd_user_secret: AQAnwihbXo+uDxAAD0HmWziVgTaAdai90IzZ6Q==
#ceph_rbd_user_secret: SHOULD_BE_REPLACED
#ceph_rbd_fsType: ext4
#ceph_rbd_imageFormat: 1
#ceph_rbd_imageFeatures: layering

# NFS-Client provisioner deployment
nfs_client_enable: true
nfs_client_is_default_class: true
# Hostname of the NFS server(ip or hostname)
nfs_server: 192.168.21.189
# Basepath of the mount point to be used
nfs_path: /exports
# NeonSAN CSI
neonsan_csi_enabled: false
neonsan_csi_is_default_class: false
# csi-neonsan container option protocol: TCP or RDMA
#neonsan_csi_protocol: TCP
# address of the NeonSAN server
#neonsan_server_address: IP:PORT
# cluster_name of the NeonSAN server
#neonsan_cluster_name: CLUSTER_NAME
# the name of the volume storage pool
#neonsan_server_pool: kube
# NeonSAN image replica count
#neonsan_server_replicas: 1
# set the increment of volumes size in GiB
#neonsan_server_stepSize: 10
# the file system to use for the volume
#neonsan_server_fsType: ext4
#client_tcp_no_delay: 1
#client_io_depth: 64
#client_io_timeout: 30
#conn_timeout: 8
#open_volume_timeout: 180
# GlusterFS  provisioner deployment
glusterfs_provisioner_enabled: false
glusterfs_is_default_class: false
#glusterfs_provisioner_storage_class: glusterfs
#glusterfs_provisioner_restauthenabled: true
# e.g. glusterfs_provisioner_resturl: http://192.168.0.4:8080
#glusterfs_provisioner_resturl: SHOULD_BE_REPLACED
# e.g. glusterfs_provisioner_clusterid: 6a6792ed25405eaa6302da99f2f5e24b
#glusterfs_provisioner_clusterid: SHOULD_BE_REPLACED
#glusterfs_provisioner_restuser: admin
#glusterfs_provisioner_secretName: heketi-secret
#glusterfs_provisioner_gidMin: 40000
#glusterfs_provisioner_gidMax: 50000
#glusterfs_provisioner_volumetype: replicate:2
# e.g. jwt_admin_key: 123456
#jwt_admin_key: SHOULD_BE_REPLACED

######################################################################
# Cluster configuration
######################################################################
## Change this to use another Kubernetes version
ks_version: 2.0.1
kube_version: v1.13.5
etcd_version: v3.2.18
#openpitrix_version: v0.3.5

ks_image_pull_policy: IfNotPresent
# Choose network plugin (calico or flannel)
kube_network_plugin: calico

# Kubernetes internal network for services, unused block of space.
kube_service_addresses: 10.233.0.0/18

# internal network. When used, it will assign IP
# addresses from this range to individual pods.
# This network must be unused in your network infrastructure!
kube_pods_subnet: 10.233.64.0/18

# Kube-proxy proxyMode configuration.
# Can be ipvs, iptables
kube_proxy_mode: ipvs

# Configure the amount of pods able to run on single node
# default is equal to application default
kubelet_max_pods: 110

# DNS configuration.
# Can be kubedns, coredns
dns_mode: coredns

# Access Port of KubeSphere
# 30000-32767 (30180/30280/30380 are not allowed)
console_port: 30880

disableMultiLogin: true

## HA(Highly Available) loadbalancer example config
## apiserver_loadbalancer_domain_name: "lb.kubesphere.local"
loadbalancer_apiserver:
  address: 192.168.21.180
  port: 6443

#Docker periodic cleaning time (Can be reboot/yearly/annually/monthly/weekly/daily/hourly)
periodic_cleaning_time: weekly
## Add other registry
docker_registry_mirrors:
  - https://registry.docker-cn.com

#Etcd periodic backup time (Specify a period in minutes)
etcd_backup_period: 30
keep_backup_number: 5
etcd_backup_dir: "/var/backups/kube_etcd"

# Monitoring
prometheus_memory_size: 400Mi
prometheus_volume_size: 20Gi

# Logging
keep_log_days: 7

kibana_enable: false
elasticsearch_volume_size: 20Gi

# Notification (Including Jenkins Notify)
## Please replace following configuration with your own mail server information.
EMAIL_SMTP_HOST: mail.example.com
EMAIL_SMTP_PORT: 25
EMAIL_FROM_ADDR: admin@example.com
EMAIL_FROM_NAME: KubeSphere
EMAIL_FROM_PASS: password
EMAIL_USE_SSL: false

# Jenkins deployment
jenkins_memory_lim: 8Gi
jenkins_memory_req: 4Gi
Java_Opts: -Xms3g -Xmx6g -XX:MaxPermSize=512m -XX:MaxRAM=8g
JenkinsLocationUrl: jenkins.devops.kubesphere.local

# harbor deployment
harbor_enable: false
harbor_domain: harbor.devops.kubesphere.local

#GitLab deployment
gitlab_enable: false
gitlab_hosts_domain: devops.kubesphere.local

## sonarqube
sonarqube_enable: true
## If you already have a sonar server,  please fill in the following parameters.
## If not, a sonarqube will be installed by default.
#sonar_server_url: SHOULD_BE_REPLACED
#sonar_server_token: SHOULD_BE_REPLACED

## Container Engine Acceleration
## Use nvidia gpu acceleration in containers
# nvidia_accelerator_enabled: true
# nvidia_gpu_nodes:
#   - kube-gpu-001

是否还有相关的配置？

**Comment by pixiake** [comment]
1.  kubectl  get pvc --all-namespaces 看下pvc是否处于pending状态
2. 如果pvc  pending，地址和路径也都配置正确的话，可以试下本地机器上是否可以挂载；如果是自建的nfs，可以看下nfs的配置参数。

**Comment by alex8158** [comment]
所有的pvc都是pending的状态。 是自建的nfs，本地也可以挂载。
# kubectl get pvc --all-namespaces 
NAMESPACE                      NAME                                               STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
kubesphere-devops-system       ks-sonarqube-postgresql                            Pending                                      nfs-client     48m
kubesphere-logging-system      data-elasticsearch-logging-data-0                  Pending                                      nfs-client     45m
kubesphere-logging-system      data-elasticsearch-logging-discovery-0             Pending                                      nfs-client     45m
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-0                 Pending                                      nfs-client     45m
kubesphere-monitoring-system   prometheus-k8s-db-prometheus-k8s-1                 Pending                                      nfs-client     45m
kubesphere-monitoring-system   prometheus-k8s-system-db-prometheus-k8s-system-0   Pending                                      nfs-client     45m
kubesphere-monitoring-system   prometheus-k8s-system-db-prometheus-k8s-system-1   Pending                                      nfs-client     45m
kubesphere-system              openldap-pvc                                       Pending                                      nfs-client     47m
kubesphere-system              redis-pvc                                          Pending                                      nfs-client     47m
openpitrix-system              openpitrix-db-pvc                                  Pending                                      nfs-client     47m
openpitrix-system              openpitrix-etcd-pvc                                Pending                                      nfs-client     47m
openpitrix-system              openpitrix-minio-pvc                               Pending                                      nfs-client     47m

**Comment by alex8158** [comment]
修改了nfs server的权限，现在所有的pvc都bound了，但还是有报错：
fatal: [ksm1]: FAILED! => {"attempts": 15, "changed": true, "cmd": "/usr/local/bin/kubectl -n openpitrix-system get pod | grep openpitrix-db-deployment | awk '{print $3}'", "delta": "0:00:00.156709", "end": "2019-06-25 15:48:46.955768", "rc": 0, "start": "2019-06-25 15:48:46.799059", "stderr": "", "stderr_lines": [], "stdout": "CrashLoopBackOff", "stdout_lines": ["CrashLoopBackOff"]}

**Comment by pixiake** [comment]
kubectl -n openpitrix-system describe pod  openpitrix-db-deployment-xxx看下这个pod的events

pod名可以通过kubectl -n openpitrix-system get pod查一下

**Comment by pixiake** [comment]
自建的nfs服务端可以这样配
 (rw,insecure,sync,no_subtree_check,no_root_squash)

**Comment by alex8158** [comment]
@pixiake  问题解决了，我执行了一次uninstall, 然后再install, 第一次出现了no matches for kind“S2iBuilderTemplate”后，接着再执行一次install, 后面就没通过了，我还是有点奇怪的是，同样是master,为什么安装成功后显示的结果不一样，master1的changed 是110，其他的只有3：
PLAY RECAP *********************************************************************************************************************************************************
kse1                       : ok=4    changed=0    unreachable=0    failed=0   
ksm1                       : ok=310  changed=110  unreachable=0    failed=0   
ksm2                       : ok=164  changed=3    unreachable=0    failed=0   
ksm3                       : ok=164  changed=3    unreachable=0    failed=0   
ksn1                       : ok=170  changed=6    unreachable=0    failed=0   
ksn2                       : ok=170  changed=6    unreachable=0    failed=0   
ksn3                       : ok=170  changed=6    unreachable=0    failed=0

**Comment by pixiake** [comment]
主要的安装步骤都在master1上完成，其他节点的话只会执行安装一些环境依赖的基础软件，所以master1上的步骤多一些

**Comment by liangyuanpeng** [comment]
我在ubuntu尝试安装 2.0.1也失败了，全新环境

FAILED - RETRYING: Kubernetes Apps | Wait for kube-apiserver (3 retries left).
FAILED - RETRYING: Kubernetes Apps | Wait for kube-apiserver (2 retries left).
FAILED - RETRYING: Kubernetes Apps | Wait for kube-apiserver (1 retries left).
fatal: [ks-allinone]: FAILED! => {"attempts": 10, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "https://127.0.0.1:6443/healthz"}

我看镜像都是
``
dockerhub.qingcloud.com下的
``

我需要怎么做？

**Comment by pixiake** [comment]
看起来是kube-apiserver不正常     docker ps看下有没有运行中的kube-apiserver
机器什么配置呢？

**Comment by liangyuanpeng** [comment]
没有运行中的kube-apiserver

```
lanren@ks-allinone:~$ sudo docker ps -a
[sudo] password for lanren: 
CONTAINER ID        IMAGE                                         COMMAND                 CREATED             STATUS              PORTS               NAMES
e3042479a969        dockerhub.qingcloud.com/coreos/etcd:v3.2.18   "/usr/local/bin/etcd"   17 hours ago        Up 17 hours                             etcd1
lanren@ks-allinone:~$ 
```

我的配置是 4C 16G 
ubuntu16

**Comment by pixiake** [comment]
虽然这个配置目前不够安装kubesphere，但应该不会在这个地方出问题，机器之前安装过k8s吗？是不是之前的/etc/kubernetes还在？

**Comment by liangyuanpeng** [comment]
@pixiake 
执行uninstall后重新install出现的是新的错误

fatal: [ks-allinone]: FAILED! => {"changed": true, "cmd": ["timeout", "-k", "600s", "600s", "/usr/local/bin/kubeadm", "init", "--config=/etc/kubernetes/kubeadm-config.yaml", "--ignore-preflight-errors=all"], "delta": "0:01:57.191283", "end": "2019-07-06 10:51:27.210557", "failed_when_result": true, "msg": "non-zero return code", "rc": 1, "start": "2019-07-06 10:49:30.019274", "stderr": "error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster", "stderr_lines": ["error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster"], "stdout": "[init] Using Kubernetes version: v1.13.5\n[preflight] Running pre-flight checks\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\n[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"\n[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"\n[kubelet-start] Activating the kubelet service\n[certs] Using certificateDir folder \"/etc/kubernetes/ssl\"\n[certs] External etcd mode: Skipping etcd/ca certificate authority generation\n[certs] External etcd mode: Skipping etcd/server certificate authority generation\n[certs] External etcd mode: Skipping etcd/peer certificate authority generation\n[certs] External etcd mode: Skipping etcd/healthcheck-client certificate authority generation\n[certs] External etcd mode: Skipping apiserver-etcd-client certificate authority generation\n[certs] Generating \"ca\" certificate and key\n[certs] Generating \"apiserver\" certificate and key\n[certs] apiserver serving cert is signed for DNS names [ks-allinone kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost ks-allinone] and IPs [10.233.0.1 192.168.1.4 192.168.1.4 10.233.0.1 127.0.0.1 192.168.1.4]\n[certs] Generating \"apiserver-kubelet-client\" certificate and key\n[certs] Generating \"front-proxy-ca\" certificate and key\n[certs] Generating \"front-proxy-client\" certificate and key\n[certs] Generating \"sa\" key and public key\n[kubeconfig] Using kubeconfig folder \"/etc/kubernetes\"\n[kubeconfig] Writing \"admin.conf\" kubeconfig file\n[kubeconfig] Writing \"kubelet.conf\" kubeconfig file\n[kubeconfig] Writing \"controller-manager.conf\" kubeconfig file\n[kubeconfig] Writing \"scheduler.conf\" kubeconfig file\n[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"\n[control-plane] Creating static Pod manifest for \"kube-apiserver\"\n[control-plane] Creating static Pod manifest for \"kube-controller-manager\"\n[control-plane] Creating static Pod manifest for \"kube-scheduler\"\n[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory \"/etc/kubernetes/manifests\". This can take up to 5m0s\n[kubelet-check] Initial timeout of 40s passed.\n[kubelet-check] It seems like the kubelet isn't running or healthy.\n[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.\n[kubelet-check] It seems like the kubelet isn't running or healthy.\n[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.\n[kubelet-check] It seems like the kubelet isn't running or healthy.\n[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.\n[kubelet-check] It seems like the kubelet isn't running or healthy.\n[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.\n[kubelet-check] It seems like the kubelet isn't running or healthy.\n[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.\n\nUnfortunately, an error has occurred:\n\ttimed out waiting for the condition\n\nThis error is likely caused by:\n\t- The kubelet is not running\n\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)\n\nIf you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:\n\t- 'systemctl status kubelet'\n\t- 'journalctl -xeu kubelet'\n\nAdditionally, a control plane component may have crashed or exited when started by the container runtime.\nTo troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.\nHere is one example how you may list all Kubernetes containers running in docker:\n\t- 'docker ps -a | grep kube | grep -v pause'\n\tOnce you have found the failing container, you can inspect its logs with:\n\t- 'docker logs CONTAINERID'", "stdout_lines": ["[init] Using Kubernetes version: v1.13.5", "[preflight] Running pre-flight checks", "[preflight] Pulling images required for setting up a Kubernetes cluster", "[preflight] This might take a minute or two, depending on the speed of your internet connection", "[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'", "[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"", "[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"", "[kubelet-start] Activating the kubelet service", "[certs] Using certificateDir folder \"/etc/kubernetes/ssl\"", "[certs] External etcd mode: Skipping etcd/ca certificate authority generation", "[certs] External etcd mode: Skipping etcd/server certificate authority generation", "[certs] External etcd mode: Skipping etcd/peer certificate authority generation", "[certs] External etcd mode: Skipping etcd/healthcheck-client certificate authority generation", "[certs] External etcd mode: Skipping apiserver-etcd-client certificate authority generation", "[certs] Generating \"ca\" certificate and key", "[certs] Generating \"apiserver\" certificate and key", "[certs] apiserver serving cert is signed for DNS names [ks-allinone kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local localhost ks-allinone] and IPs [10.233.0.1 192.168.1.4 192.168.1.4 10.233.0.1 127.0.0.1 192.168.1.4]", "[certs] Generating \"apiserver-kubelet-client\" certificate and key", "[certs] Generating \"front-proxy-ca\" certificate and key", "[certs] Generating \"front-proxy-client\" certificate and key", "[certs] Generating \"sa\" key and public key", "[kubeconfig] Using kubeconfig folder \"/etc/kubernetes\"", "[kubeconfig] Writing \"admin.conf\" kubeconfig file", "[kubeconfig] Writing \"kubelet.conf\" kubeconfig file", "[kubeconfig] Writing \"controller-manager.conf\" kubeconfig file", "[kubeconfig] Writing \"scheduler.conf\" kubeconfig file", "[control-plane] Using manifest folder \"/etc/kubernetes/manifests\"", "[control-plane] Creating static Pod manifest for \"kube-apiserver\"", "[control-plane] Creating static Pod manifest for \"kube-controller-manager\"", "[control-plane] Creating static Pod manifest for \"kube-scheduler\"", "[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory \"/etc/kubernetes/manifests\". This can take up to 5m0s", "[kubelet-check] Initial timeout of 40s passed.", "[kubelet-check] It seems like the kubelet isn't running or healthy.", "[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.", "[kubelet-check] It seems like the kubelet isn't running or healthy.", "[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.", "[kubelet-check] It seems like the kubelet isn't running or healthy.", "[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.", "[kubelet-check] It seems like the kubelet isn't running or healthy.", "[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.", "[kubelet-check] It seems like the kubelet isn't running or healthy.", "[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.", "", "Unfortunately, an error has occurred:", "\ttimed out waiting for the condition", "", "This error is likely caused by:", "\t- The kubelet is not running", "\t- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)", "", "If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:", "\t- 'systemctl status kubelet'", "\t- 'journalctl -xeu kubelet'", "", "Additionally, a control plane component may have crashed or exited when started by the container runtime.", "To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.", "Here is one example how you may list all Kubernetes containers running in docker:", "\t- 'docker ps -a | grep kube | grep -v pause'", "\tOnce you have found the failing container, you can inspect its logs with:", "\t- 'docker logs CONTAINERID'"]}

初始化first master超时，一开始以为是镜像的问题，去下载了``k8s.gcr.io``下的v1.13.5版本的images也没有用  

辛苦帮忙看看是什么问题

**Comment by pixiake** [comment]
感觉是有旧的配置文件残留，环境可以远程吗？可以的话相关信息可以发到kubesphere@yunify.com

**Comment by pixiake** [comment]
环境可以远程吗？可以的话相关信息可以发到kubesphere@yunify.com   或者也可以登录https://console.qingcloud.com提工单

**Comment by pixiake** [comment]
看下kubelet启动了么？systemctl  status  kubelet

**Comment by xianhuadezhuren** [comment]
> @pixiake 问题解决了，我执行了一次uninstall, 然后再install, 第一次出现了no matches for kind“S2iBuilderTemplate”后，接着再执行一次install, 后面就没通过了，我还是有点奇怪的是，同样是master,为什么安装成功后显示的结果不一样，master1的changed 是110，其他的只有3：
> PLAY RECAP *********************************************************************************************************************************************************
> kse1 : ok=4 changed=0 unreachable=0 failed=0
> ksm1 : ok=310 changed=110 unreachable=0 failed=0
> ksm2 : ok=164 changed=3 unreachable=0 failed=0
> ksm3 : ok=164 changed=3 unreachable=0 failed=0
> ksn1 : ok=170 changed=6 unreachable=0 failed=0
> ksn2 : ok=170 changed=6 unreachable=0 failed=0
> ksn3 : ok=170 changed=6 unreachable=0 failed=0

你好，你是怎么解决的，我也碰到了类似的情况，ks-jenkins安装碰到遇到这个情况，还望给予解答
