### ISSUE TITLE
Can not access edge-node shell and logs after upgrade form v3.2.0 to v3.3.0-rc.3.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/kubesphere#5002]
**Describe the Bug**
After upgrade to v3.3.0-rc.3, I can not access edge-node shell and logs.
On my newly added edge node after upgrade to v3.3.0-rc.3, I can't access the node terminal and view the pod log either.

I find daemonset iptables of kubeedge is still exist.
![image](https://user-images.githubusercontent.com/68640256/175921393-4648f8e1-56d9-446f-a0c0-6474f98259c5.png)
![image](https://user-images.githubusercontent.com/68640256/175921458-c62c5984-7622-43fc-a789-1dda027b8d87.png)

**Versions Used**
KubeSphere:  `v3.3.0-rc.3`
Kubernetes:  `v1.21.0`

**Comment by wenchajun** [comment]
For upgrades at the edge, please refer to the official documentation.https://kubeedge.io/zh/docs/setup/upgrade/
If you should handle it this way in the cloud, delete `iptables`, because the new version has removed `iptables`. If this still does not work, it is recommended to delete all resources under the `kubeedge` namespace and then delete the `kubeedge` namespace.Then execute the following command：
```
kubectl edit cc -n kubesphere-system
```
Then just delete the `edgeruntime` field under status and restart `ks-installer`.
