### ISSUE TITLE
where is the openpitrix dashboard?

### ISSUE THREAD

**Issue by dotw** [kubesphere/kubesphere#503]
**Describe the bug(描述下问题)**
can't find openpitrix dashboard

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.0.1

**Environment(环境的硬件配置)**
All-In-One Ubuntu 16.04 with 8C, 16GB

**To Reproduce(复现步骤)**
There is no entry point for opentrix dashboard

**Expected behavior(预期行为)**
There should have one entry for opentrix dashboard since this component is installed by default.

**Comment by FeynmanZhou** [comment]
Hi @dotw ，

We suggest you to install the latest version of OpenPitrix (v0.4) manually, it includes the OpenPitrix dashboard and more features, pls refer to the [OpenPitrix instruction](https://openpitrix.io/install). Since the inner OpenPitrix version is still v0.3.5 which doesn't contain the dashboard, it will be upgraded to v0.4 in the next iteration.

Any questions, please let me know.
Thanks.

**Comment by dotw** [comment]
@FeynmanZhou How to use it if we don't have a dashboard in the current release? only REST API?

**Comment by FeynmanZhou** [comment]
@dotw REST API is allowed,actually we suggest you to install KubeSphere v2.1-dev,  it has app store and management which is originated from  OpenPitrix v0.4.
