### ISSUE TITLE
发布模式: 蓝绿部署：发布任务后任务下线按钮缺失

### ISSUE THREAD

**Issue by ccenjie** [kubesphere/kubesphere#5360]
使用的版本 v3.3.1
使用实例应用测试灰度发布
![QQ截图20221110121232](https://user-images.githubusercontent.com/18629033/200999187-8fa7bf18-cfee-4259-be16-8f54f825418a.png)

**Comment by hongzhouzi** [comment]
There should be a delete button here, the downline button is not here. You can open the browser console to see if there is an error message.

**Comment by ccenjie** [comment]
> There should be a delete button here, the downline button is not here. You can open the browser console to see if there is an error message.

没有任何错误，如果下线按钮不在这，我应该如何把这个任务删除呢
![QQ截图20221111163731](https://user-images.githubusercontent.com/18629033/201300432-166d0805-81d4-4443-b7b6-6a4683952e3d.png)

**Comment by hongzhouzi** [comment]
This is not quite as expected, you can try to deploy bookinfo project to see if it works, if not, you can describe the steps to reproduce it. Also try to use English here, Chinese questions can be asked on the [kubesphere Chinese forum](https://kubesphere.com.cn/forum/), thanks.

**Comment by hongzhouzi** [comment]
This problem may be caused by permissions, what permissions the current operation is in?

**Comment by ccenjie** [comment]
项目管理员身份

**Comment by zhou1203** [comment]
Hi, thank you very much for reporting this bug. We will fix it at next release. But now, If you want to delete the Graysacle Release, you should be logged in as platform admin.

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-installer:release-3.3`


![image](https://user-images.githubusercontent.com/68640256/212638179-a6608e29-cc5e-4fb3-8f28-c00fb4069c2a.png)

![image](https://user-images.githubusercontent.com/68640256/212637928-55e1f338-d1ee-4aa6-97c0-9c3447b31d2f.png)

![image](https://user-images.githubusercontent.com/68640256/212637834-12a1a8dd-99b9-402d-ad5c-07ce07246838.png)
![image](https://user-images.githubusercontent.com/68640256/212637892-dba890a2-f24c-4963-9b97-85b83aa31848.png)
