### ISSUE TITLE
Devops project issues

### ISSUE THREAD

**Issue by chenshengshi** [kubesphere/kubesphere#5633]
The devops project cannot pull the private image of the mirror when constructing the image. (Note: The local daemon.json has already configured a private warehouse to pull the image.)

 I can manually enter the container during construction and pull it out

May I ask how to solve my problem? Thank you

![image](https://user-images.githubusercontent.com/43060901/230813366-af2b98c9-6e3b-4671-baa2-aad02e52df71.png)
![image](https://user-images.githubusercontent.com/43060901/230813605-b9738a0b-6ecf-4ba8-ab23-d3585e4e9207.png)

**Comment by wansir** [comment]
@chenshengshi This error message means that Jenkins was refused by the server when attempting to connect to Harbor using HTTPS protocol because Harbor only accepts HTTPS connections instead of HTTP connections. This could be because Jenkins is not correctly configured to use HTTPS connection.

To solve this problem, you can check the configuration of Jenkins and make sure that HTTPS connection is used. If you are already using HTTPS connection, please make sure that the certificate is correct or try disabling SSL verification in the configuration of Jenkins.

Additionally, you can also check the configuration of Harbor to ensure that HTTPS connection is correctly configured and SSL certificate is enabled.
