### ISSUE TITLE
Fix the UI error of APP store and workload.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5726]
- [ ] https://github.com/kubesphere/issues/issues/954
- [ ] https://github.com/kubesphere/issues/issues/941
- [ ] https://github.com/kubesphere/issues/issues/963

**Comment by luqiaoshi** [comment]
Issue fixed in
workloads仅有一条数据，UI遮挡 ---done
![image](https://github.com/kubesphere/kubesphere/assets/24789703/4367737d-a500-4e8b-88a8-5b882a67083d)
应用商店，企业空间/项目名超长，UI遮挡 ---done
![image](https://github.com/kubesphere/kubesphere/assets/24789703/1e347134-ea8b-4941-b409-bf52c30186c8)
资源存在，提示信息已修正
![image](https://github.com/kubesphere/kubesphere/assets/24789703/0cba8ca8-c851-4f47-9029-dfa9e712d382)
