### ISSUE TITLE
Update webhook notification config error

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/kubesphere#5758]
https://github.com/kubesphere/issues/issues/241
**Describe the Bug**

For UI issues please also add a screenshot that shows the issue.

**Versions Used**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by luqiaoshi** [comment]
Issue fixed in `ks v3.4.0-rc.0`
无需认证：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/ea5382da-8a36-44e7-ba4a-db697230fb41)
Bearer令牌：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/d8506201-bed2-4933-8ad7-8541e4b7bc0a)
基础认证：
![image](https://github.com/kubesphere/kubesphere/assets/24789703/d857074c-c1cc-45cf-8755-ad1c1b5f64e7)
