### ISSUE TITLE
【Project】Enable project gateway fail，field is invalid

### ISSUE THREAD

**Issue by luqiaoshi** [kubesphere/kubesphere#5806]
**Describe the Bug**
Steps：
1.click【Access Control】，select workspaces，enter detail
2.click 【Projects】-【Gateway Setting】：Enable Gateway，info correct-》OK
Actual：
post fail，field is invalid：metadata.name: Required value: name or generateName is required

![image](https://github.com/kubesphere/kubesphere/assets/24789703/ebfdb730-5a8f-4640-aac7-8dd190f50176)

**Versions Used**
KubeSphere: `v3.4.0-rc.0`
Kubernetes: (If KubeSphere installer used, you can skip this)
```
root@node1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDa GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDa GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**

**Expected behavior**

**Comment by hongzhouzi** [comment]
<img width="848" alt="WeChatWorkScreenshot_9244c55b-8fb8-42e2-bfd3-97c1bd2d9220" src="https://github.com/kubesphere/kubesphere/assets/36416216/6f189ddf-3f8a-47dd-ab44-8619e41dd48d">

Previously, when creating the gateway front-end parameters did not pass metadata.name because, this is generated according to the project name. After the addition of a global check all resources must pass some mandatory parameters, here you need to pass this parameter front-end, otherwise there will be this error:

![WeChatWorkScreenshot_9bdf9933-44b1-4ea3-bc2e-fe04ec5e3cda](https://github.com/kubesphere/kubesphere/assets/36416216/33e276bc-a49d-4064-9138-3b707682828c)

**Comment by hongzhouzi** [comment]
<img width="564" alt="image" src="https://github.com/kubesphere/kubesphere/assets/36416216/0e2c0981-17dc-4ce7-81dc-92e91c581d7f">

In addition, you need to remove the last / in the gateway request, otherwise the data will not be requested
<img width="1037" alt="image" src="https://github.com/kubesphere/kubesphere/assets/36416216/b46a2c0b-df6c-4b7d-b5f1-ba70887d5233">
