### ISSUE TITLE
【upgrade】ks3.3.2->ks3.4.0, external ldap account authentication fails

### ISSUE THREAD

**Issue by sigboom** [kubesphere/kubesphere#5862]
**Describe the Bug**
use ks-installer update Cluster successfully，but I can't login ks like v3.3.2
![image](https://github.com/kubesphere/kubesphere/assets/34954447/b707079a-6c76-42df-a873-9d67d26dfdef)

**Versions Used**
KubeSphere: v3.4.0
Kubernetes: KubeSphere installer

**How To Reproduce**
1. config ldap like this picture
![image](https://github.com/kubesphere/kubesphere/assets/34954447/feedd3a8-d275-41b7-a445-8690cd88854d)

2. update ks-installer from v3.3.2 to v3.4.0
3. login fail 

**Expected behavior**

**Comment by snipking** [comment]
same here

**Comment by variamus** [comment]
Hello,
same problem here even though there was a commit as corrective action.
I don't know how can we apply the temporary fix suggested on a running kubesphere installation, can you provide some guidelines ?
Thank you

**Comment by yakexi007** [comment]
I upgraded from 3.3.1 to 3.4.0, The same problem arises，external ldap login failed, the following error occurred.

2023/10/17 09:05:21 http: TLS handshake error from 172.22.10.11:54950: remote error: tls: bad certificate
E1017 09:05:21.442340 1 basecontroller.go:132] error syncing 'abc-b8bm8' in loginrecord-controller: Internal error occurred: failed calling webhook "users.iam.kubesphere.io": failed to call webhook: Post "[https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s](https://ks-controller-manager.kubesphere-system.svc/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s)": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ks-controller-manager-ca"), requeuing

**Comment by littleBlackHouse** [comment]
> I upgraded from 3.3.1 to 3.4.0, The same problem arises，external ldap login failed, the following error occurred.
> 
> 2023/10/17 09:05:21 http: TLS handshake error from 172.22.10.11:54950: remote error: tls: bad certificate E1017 09:05:21.442340 1 basecontroller.go:132] error syncing 'abc-b8bm8' in loginrecord-controller: Internal error occurred: failed calling webhook "users.iam.kubesphere.io": failed to call webhook: Post "[https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s](https://ks-controller-manager.kubesphere-system.svc/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s)": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ks-controller-manager-ca"), requeuing

it will fixed in v3.4.1

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/9ed10ca6-e3c6-4144-95e5-b5a9232cfbe7)

**Comment by zjpjly** [comment]
it seems your login page is not new, your page dont have ldap button to switch ldap login page.
