### ISSUE TITLE
3.4.0:TypeError: Cannot read properties of undefined (reading 'slice')

### ISSUE THREAD

**Issue by DoNotBugPlz** [kubesphere/kubesphere#5873]
<img width="1884" alt="image" src="https://github.com/kubesphere/kubesphere/assets/42760659/c1697b0a-bd47-4328-ba0a-192451ae8a61">

KubeSphere: 3.4.0
Kubernetes:  1.26.5

**Comment by lishuyanla** [comment]
I have also encountered this issue. I just installed it and the application repository and template are still working properly. After a day, I started reporting errors and cannot use them anymore.

**Comment by lishuyanla** [comment]
![image](https://github.com/kubesphere/kubesphere/assets/40929609/9a14c4a6-4815-472b-bec7-17a4a3085a18)
Application Warehouse 404 Not Found

**Comment by ic0xgkk** [comment]
It caused by redundant `/` in request url.

![image](https://github.com/kubesphere/kubesphere/assets/11086634/f74a8c87-f51c-40ca-b4ec-c2cd9097769d)

I debug it and remove the `/` below, it works fine.
![image](https://github.com/kubesphere/kubesphere/assets/11086634/dae50b37-9989-4cd1-95c2-7ff15f973b1e)
 
![image](https://github.com/kubesphere/kubesphere/assets/11086634/8d77cd3d-fdba-495a-947b-3ccc1badae6f)

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/e749cfd9-1a11-4e27-9692-e72399c7eb8c)
