### ISSUE TITLE
kubesphere v3.4.0 notification channel report certificate signed by unknown authority

### ISSUE THREAD

**Issue by jinyan-328** [kubesphere/kubesphere#5896]
Internal error occurred: conversion webhook for notification.kubesphere.io/v2beta1, Kind=Receiver failed: Post "https://notification-manager-webhook.kubesphere-monitoring-system.svc:443/convert?timeout=30s": x509: certificate signed by unknown authority

**Comment by kit101** [comment]
+1

**Comment by hohoangkha** [comment]
I have the same error

**Comment by jiahuilong** [comment]
https://notification-manager-webhook.kubesphere-monitoring-system.svc:443/convert?timeout=30s": x509: certificate signed by unknown authority

**Comment by hohoangkha** [comment]
> After upgrading from V3.3 to V3.4.0 and enabling the alerting components, I encountered the same issue. I fixed it by using the following command:
> 
> ```shell
> caBundle=$(kubectl get validatingWebhookConfiguration notification-manager-validating-webhook -o jsonpath='{.webhooks[0].clientConfig.caBundle}')
> 
> cat > /tmp/patch.yaml <<EOF
> spec:
>   conversion:
>     webhook:
>       clientConfig:
>         caBundle: ${caBundle}
>         service:
>           namespace: kubesphere-monitoring-system
> EOF
>               
> kubectl patch crd configs.notification.kubesphere.io --type=merge --patch-file /tmp/patch.yaml
> kubectl patch crd receivers.notification.kubesphere.io --type=merge --patch-file /tmp/patch.yaml
> ```
> 
> Refer to:
> 
> * https://ask.kubesphere.io/forum/d/8130-notification-manager/12

Thank you so much. <3

**Comment by yakexi007** [comment]
2023/10/17 09:05:21 http: TLS handshake error from 172.22.10.11:54950: remote error: tls: bad certificate
E1017 09:05:21.442340       1 basecontroller.go:132] error syncing 'alex.zhang-b8bm8' in loginrecord-controller: Internal error occurred: failed calling webhook "users.iam.kubesphere.io": failed to call webhook: Post "https://ks-controller-manager.kubesphere-system.svc:443/validate-email-iam-kubesphere-io-v1alpha2?timeout=30s": tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "ks-controller-manager-ca"), requeuing 

/help

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/kubesphere/assets/18654693/4f1b75cb-ea13-4071-8369-e1f5de95343e)
