### ISSUE TITLE
KubesphereNamespace is hard-coded and fails to log in with the initial admin account

### ISSUE THREAD

**Issue by sungik8221** [kubesphere/kubesphere#6310]
## General remarks

This issue is related to the deployment of KubeSphere in a custom namespace, which results in login failures due to a hardcoded variable. Below are the details.

---

**What's your question**

After deploying KubeSphere in a namespace other than `kubesphere-system`, the login functionality fails. The root cause is the variable `KubesphereNamespace`, which is hardcoded to `"kubesphere-system"`. This restricts proper namespace configuration during deployment and causes authentication errors when using a custom namespace.

![image](https://github.com/user-attachments/assets/bb5853c0-faee-4470-bb1a-120f995a2f61)

---

**Environment: OS & Hardware Information**

- **Environment**: Bare Metal
- **Kubernetes Version**: v1.
- **Kubesphere Version**: v4.1.2

---

**Error logs or message (Attach logs or screenshot)**

- **Error Message**: 
```text
{
  code: 400,
  error: 'invalid_client',
  error_description: 'The provided client_id is invalid or does not exist.',
  statusText: 'Bad Request'
}
  --> POST /login 200 5ms 81b 2024/12/11T16:12:20.306```

**Comment by wansir** [comment]
@sungik8221 

As you can see, we currently do not support changing the namespace of a KubeSphere deployment. The "kubesphere-system" namespace is relied upon by other extension components and configurations. Keeping a stable namespace name helps prevent issues caused by unpredictable configuration changes and also reduces the cost of debugging and troubleshooting.
